### ISSUE TITLE
guard里的全局css影响了原有的样式表

### ISSUE THREAD

**Issue by iyjian** [Authing/Guard#56]
我现在引入了guard的组件，但是下面的css把我的样式给弄紊乱了。

```css
* {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}

:after,
:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}

```

代码地址 https://github.com/Authing/Guard/blob/master/src/styles/styles.css#L10
